// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcbGXNtowCdfYbPr6qR4wDQ983HzoZHPg',
    appId: '1:601960279501:web:87331882dc32e4fce92884',
    messagingSenderId: '601960279501',
    projectId: 'quiz-app-5cc5c',
    authDomain: 'quiz-app-5cc5c.firebaseapp.com',
    storageBucket: 'quiz-app-5cc5c.firebasestorage.app',
    measurementId: 'G-0EWC5R6HQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAja8DSG2DQFObCSF_0JrNfZenopxz19wU',
    appId: '1:601960279501:android:dfd0ae79bcc97442e92884',
    messagingSenderId: '601960279501',
    projectId: 'quiz-app-5cc5c',
    storageBucket: 'quiz-app-5cc5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjvxPS3sWVVmJ-4l6PXqYLcpaZRsOV8E',
    appId: '1:601960279501:ios:0f92f8108f9679b0e92884',
    messagingSenderId: '601960279501',
    projectId: 'quiz-app-5cc5c',
    storageBucket: 'quiz-app-5cc5c.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjvxPS3sWVVmJ-4l6PXqYLcpaZRsOV8E',
    appId: '1:601960279501:ios:0f92f8108f9679b0e92884',
    messagingSenderId: '601960279501',
    projectId: 'quiz-app-5cc5c',
    storageBucket: 'quiz-app-5cc5c.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcbGXNtowCdfYbPr6qR4wDQ983HzoZHPg',
    appId: '1:601960279501:web:b314a04e96da6757e92884',
    messagingSenderId: '601960279501',
    projectId: 'quiz-app-5cc5c',
    authDomain: 'quiz-app-5cc5c.firebaseapp.com',
    storageBucket: 'quiz-app-5cc5c.firebasestorage.app',
    measurementId: 'G-K9QD3QDJEQ',
  );
}
